; Zur Referenz:
;(defun set-rhythm (bnum bden minduration))
;(defun set-harmony (keyname))
; hier evtl. noch den last-tone an die Übung angepasst definieren

(defvar figure-string "")
(defvar lily-string "")
(defvar *temp-diat* '(c d e f g a b))
(defvar *reft* 48)  ;added in Jan 2026 to adapt to V9 (*reft* was earlier 12)
	
(defvar *ex01* (make-exercise-type))
  (setf (exercise-type-title *ex01*) "Handel No1")
  (setf (exercise-type-tostri *ex01*) "c2 g' | e a | f c' | a f | g a | f g | c,1 ")
  (setf (exercise-type-lasttone *ex01*) "c")
  (setf (exercise-type-lasttcount *ex01*) *reft*)
  (setf (exercise-type-rnum *ex01*) 4)
  (setf (exercise-type-rden *ex01*) 4) 
  (setf (exercise-type-harm *ex01*) "cmaj")
  
(defvar *ex02* (make-exercise-type))
  (setf (exercise-type-title *ex02*) "Handel No2")
  (setf (exercise-type-tostri *ex02*) "g4 g' e c | d b e a, | d g, c a | e' c g' e | b' g d' d, | e c d2 | g1 ")
  (setf (exercise-type-lasttone *ex02*) "c")
  (setf (exercise-type-lasttcount *ex02*) *reft*)
  (setf (exercise-type-rnum *ex02*) 4)
  (setf (exercise-type-rden *ex02*) 4) 
  (setf (exercise-type-harm *ex02*) "gmaj")

(defvar *ex03* (make-exercise-type))
  (setf (exercise-type-title *ex03*) "Handel No3")
  (setf (exercise-type-tostri *ex03*) "f8 g f e d a' d c bes c bes a g f g g, c d c bes a g f a bes a g bes c bes a c d c d e f4 bes, c2 f,")
  (setf (exercise-type-figstri *ex03*) "s1 s1 s1 s1 <6>4. <6_5>8 s2 s1")
  (setf (exercise-type-lasttone *ex03*) "c")
  (setf (exercise-type-lasttcount *ex03*) *reft*)
  (setf (exercise-type-rnum *ex03*) 4)
  (setf (exercise-type-rden *ex03*) 4)
  (setf (exercise-type-harm *ex03*) "fmaj")
  (setf (exercise-type-droplist *ex03*) '(2 3 4 6 7 8 10 11 12 14 15 16  18 19 20 22 24 26 28 30 32 34 35))

(defvar *ex07* (make-exercise-type))
  (setf (exercise-type-title *ex07*) "Handel No7")
  (setf (exercise-type-tostri *ex07*) "g8 g' fis d e fis g b, c d e fis g fis g e a fis g a d, d' b a g fis e c d g, d' d, g1")
  (setf (exercise-type-figstri *ex07*) "s4 <6> <6>8 <6> s8 <6> <6> <6> <6> <6> s8 s8 <6> s8 <_+> <6> s8 <_+> s8 s8 <6> <6> <6> <6> <6> s8 s4 <4>8 <3>8 s1")
  (setf (exercise-type-lasttone *ex07*) "c")
  (setf (exercise-type-lasttcount *ex07*) *reft*)
  (setf (exercise-type-rnum *ex07*) 4)
  (setf (exercise-type-rden *ex07*) 4)
  (setf (exercise-type-harm *ex07*) "gmaj")
  (setf (exercise-type-droplist *ex07*) '(2 4 8 14 16 22 28))

(defvar *ex11* (make-exercise-type))
  (setf (exercise-type-title *ex11*) "Handel No11")
  (setf (exercise-type-tostri *ex11*) "e8 d e c f g a bes c bes c c, d e f g a g a a, d c d e f e f bes, c4 c, f1")
  (setf (exercise-type-figstri *ex11*) "<6>4 <6> r <6> <4> <3> r <6> <4> <3> <6> <6> <4> <3> <4> <3> s1")
  (setf (exercise-type-lasttone *ex11*) "c")
  (setf (exercise-type-lasttcount *ex11*) *reft*)
  (setf (exercise-type-rnum *ex11*) 4)
  (setf (exercise-type-rden *ex11*) 4) 
  (setf (exercise-type-harm *ex11*) "fmaj")
  (setf (exercise-type-droplist *ex11*) '(2 3 4 6 7 8 10 12 14 15 16 18 20 22 23 24 26 28))

(defvar *ex12* (make-exercise-type))
  (setf (exercise-type-title *ex12*) "Handel No12")
  (setf (exercise-type-tostri *ex12*) "d'4 c bes c a bes g a8 g f e d c bes4 c8 bes f4 bes8 a g4 a d2")
  (setf (exercise-type-figstri *ex12*) "r2 <6_5>4 r <6_5> r <6_5> <_+> <6>2 <6_5>4 r <6_5> <_+> r2")
  (setf (exercise-type-lasttone *ex12*) "d")
  (setf (exercise-type-lasttcount *ex12*) *reft*)
  (setf (exercise-type-rnum *ex12*) 4)
  (setf (exercise-type-rden *ex12*) 4) 
  (setf (exercise-type-harm *ex12*) "dmin")
  (setf (exercise-type-droplist *ex12*) '(3 16 18 19 20 24 27))

(defvar *zk05* (make-exercise-type))
  (setf (exercise-type-title *zk05*) "Zackor No5")
  (setf (exercise-type-tostri *zk05*) "g'4 e fis d e cis d d c a b g d' fis g2")
  (setf (exercise-type-figstri *zk05*) "r4 r <6> r r <6> r2 r4 <6> <6>  r r <6> r2")
  (setf (exercise-type-lasttone *zk05*) "c")
  (setf (exercise-type-lasttcount *zk05*) *reft*)
  (setf (exercise-type-rnum *zk05*) 4)
  (setf (exercise-type-rden *zk05*) 4) 
  (setf (exercise-type-harm *zk05*) "gmaj")
  (setf (exercise-type-droplist *zk05*) '(15))

(defvar *zk06* (make-exercise-type))
  (setf (exercise-type-title *zk06*) "Zackor No6")
  (setf (exercise-type-tostri *zk06*) "g'4 b fis d g a d,2 c4 b c g d' d g,2")
  (setf (exercise-type-figstri *zk06*) "r4 <6> <6> r r <_+> r r r <6> r r <4> <7> r2")
  (setf (exercise-type-lasttone *zk06*) "c")
  (setf (exercise-type-lasttcount *zk06*) *reft*)
  (setf (exercise-type-rnum *zk06*) 4)
  (setf (exercise-type-rden *zk06*) 4) 
  (setf (exercise-type-harm *zk06*) "gmaj")
  (setf (exercise-type-droplist *zk06*) '())



(defun set-exercise (exc)
  (progn
    (set-rhythm (exercise-type-rnum exc) (exercise-type-rden exc) (exercise-type-rmin exc))
	(set-harmony (exercise-type-harm exc))
    (setf *mindur* (rhythm-context-mindur *rhythm*)) ; aus Kompatibilitätsgründen, wird evtl. noch verbessert
    (setf (tone-name *last-tone*) "c")
    (setf (tone-oct *last-tone*) 'k)
    (setf (tone-num *last-tone*) *reft*)
    (setf (tone-dur *last-tone*) *mindur*)
    (setf (tone-dot *last-tone*) 0)
    (setf (tone-bea *last-tone*) 0)
    (setf *dietoene* '())
    (setq lily-string (exercise-type-tostri exc))
    (setq figure-string (exercise-type-figstri exc))
    (erzeuge-actr-toene *mindur* lily-string figure-string)
    (unless (null (exercise-type-droplist exc))
 	  (dolist (ele (exercise-type-droplist exc) 'done) (nocho ele)))
  )
)
